version: '3.4'

services:
  keycloak:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./providers:/opt/keycloak/providers:ro
      - ./themes:/opt/keycloak/themes:ro
      - ./conf:/opt/keycloak/conf:ro
      - ./import/test-realm.json:/opt/keycloak/data/import/test-realm.json
      - keycloak_logs:/opt/keycloak/log
    command: >
      -c "./bin/kc.sh start-dev
      -Dkeycloak.migration.action=import
      -Dkeycloak.migration.provider=singleFile
      -Dkeycloak.migration.file=/opt/keycloak/data/import/test-realm.json
      -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    ports:
      - 8080:8080
    networks:
      - keycloak_network
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: 5432
      QUARKUS_HTTP_HOST: 0.0.0.0
      KEYCLOAK_FRONTEND_URL: http://localhost:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgresql_network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_PORT: 5432
    restart: always

volumes:
  postgres_data:
  keycloak_logs:

networks:
  postgresql_network:
  keycloak_network: